### ISSUE TITLE
compatibility issues

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [excalibeur/pf2e-bardic-inspiration#3]
will this be updated for the newest version as currently it doesnt work. or apply the effect.

**Comment by ThingsCouldGetDicey** [comment]
okay the actual issue is the module manifest is pointing to the older version when you update. id appreciate it if you changed to the newest version so i could run it thank you. :)

**Comment by excalibeur** [comment]
I've updated the Foundry VTT listing to have version 1.2.0, 10.286 min core version, should be good to go if you have the latest update

**Comment by excalibeur** [comment]
Also updated version 1.0.0 to have Max core version of 0.8.9 due to the changes from the new core version (10+)
