### ISSUE TITLE
Compatibility warnings

### ISSUE THREAD

**Issue by AFigureOfBlue** [excalibeur/pf2e-bardic-inspiration#4]
On Foundry v10 build 291, and PF2e system version 4.7.4, I get the following compatibility warnings when installing this module:

- The module "pf2e-bardic-inspiration" is using "author" which is deprecated in favor of "authors"
- module "pf2e-bardic-inspiration" contains the "systems" field which is deprecated in favor of "relationships.systems"

**Comment by excalibeur** [comment]
Just made a new version 1.2.1, tested with foundry 10.291 and pf2e 4.74. Should remove those warnings. Also updated on the foundry module list.

**Comment by AFigureOfBlue** [comment]
It does seem to be fixed now! Thank you.
