### ISSUE TITLE
v11 compatibility issues

### ISSUE THREAD

**Issue by chaoticnote** [excalibeur/pf2e-bardic-inspiration#7]
Seems to have issues working with Foundry v11 Build 299. Unfortunately, I can't seem to get the error message on why that is.

![image](https://github.com/excalibeur/pf2e-bardic-inspiration/assets/28378016/8ab0bdec-fed9-42a3-b069-5ab14fbaa224)

**Comment by excalibeur** [comment]
This error is due to the maximum core version being 10. 
Foundry has added core v11, which I don't think pf2e is updated for yet. Once it is, I'll add a version compatible with v11

**Comment by dogstarrb** [comment]
pf2e system has been out of beta for a few weeks now, can we expect a v11 version soon?

**Comment by excalibeur** [comment]
Version 1.3.0 now out and works with 11.305
