### ISSUE TITLE
The +1 Inspire Courage and +1 Inspire Defense effects are not applying

### ISSUE THREAD

**Issue by Rayquaza1090** [excalibeur/pf2e-bardic-inspiration#9]
It is perfectly fine with all other variations (+2/3 for both) but the first rank ones simply do nothing when clicked.

**Comment by excalibeur** [comment]
Looks like it's due to the PF2e remaster spell name changes in the newest system version - working on it

**Comment by excalibeur** [comment]
I have released version 1.4.0 which should work with the remastered spell changes - Please let me know if you have any other issues!
